server:
  port: 8080

spring:
  datasource:
    username: root
    password: mysqlserverwellcom
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

indexing-settings:
  sites:
    - url: http://www.playback.ru/
      name: PlayBack
    - url: http://www.svetlovka.ru/
      name: Svetlovka


jsoup:
  user_agent: searchBotProject
  referrer: http://www.google.com
  timeout_min: 50
  timeout_max: 150